/* eslint-disable */
/* This file is auto-generated by Convex. Do not edit manually. */
/* Stub generated for offline development — replaced by `bunx convex dev` */

import {
    actionGeneric,
    httpActionGeneric,
    queryGeneric,
    mutationGeneric,
    internalActionGeneric,
    internalMutationGeneric,
    internalQueryGeneric,
} from 'convex/server';
import type { DataModel } from './dataModel';

export const query = queryGeneric as typeof queryGeneric<DataModel>;
export const mutation = mutationGeneric as typeof mutationGeneric<DataModel>;
export const action = actionGeneric as typeof actionGeneric<DataModel>;
export const httpAction = httpActionGeneric;
export const internalQuery = internalQueryGeneric as typeof internalQueryGeneric<DataModel>;
export const internalMutation =
    internalMutationGeneric as typeof internalMutationGeneric<DataModel>;
export const internalAction = internalActionGeneric as typeof internalActionGeneric<DataModel>;
